# Generated by Django 3.1.2 on 2020-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Complete', max_length=20),
        ),
    ]
