# Generated by Django 3.1.2 on 2020-10-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0003_senderemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='subject',
            field=models.CharField(default='Email Subject', max_length=200),
        ),
    ]
